// Build the Spatial Adjust guide system into a self-contained static bundle.
//
// The Core Design export depends on unpkg.com at runtime and resolves component
// imports with fetch(). Both are removed here without forking support.js, by using
// two hooks the dc-runtime already supports:
//
//   window.__resources      URL -> replacement URL. cdnScriptFor() consults this before
//                           falling back to the unpkg URL, so React/ReactDOM load locally.
//                           Its mere presence also stops boot() re-fetching location.href.
//   window.__resourceBlobs  URL -> Blob. bundledBlob() consults this before fetch(), so the
//                           imported SpatialAdjustApp component is inlined rather than
//                           requested. This is what restores file:// support.
//
// Keeping support.js untouched preserves the Core Design -> web round-trip: re-exporting
// from Core Design means dropping the new .dc.html files in and rebuilding.

import { readFile, writeFile, mkdir, rm, cp } from 'node:fs/promises';
import { join } from 'node:path';

const ROOT = import.meta.dirname;
const DIST = join(ROOT, 'dist');

const ENTRY = 'Learn Spatial Adjust.dc.html';
const COMPONENTS = ['SpatialAdjustApp'];

// Copied verbatim into dist. Everything else (screenshots/, uploads/, .thumbnail,
// node_modules/, scripts/) is Core Design tooling or build-time only and must not ship.
const STATIC_DIRS = ['assets', '_ds', 'vendor'];

// Design-system files that never execute or render at runtime.
//
// _ds_bundle.js is a 10MB React component library (Fluent icons + Oasis components). Neither
// .dc.html file references the ToroOasisDesignSystem namespace or any component from it — the
// guides style themselves purely with the CSS custom properties in tokens/. Verified by
// scripts/compare-guides.mjs: fingerprints across all 7 guides are identical with it blocked.
// The others are lint config, build metadata, and docs, referenced by nothing.
const DS_EXCLUDE = ['_ds_bundle.js', '_ds_manifest.json', '_adherence.oxlintrc.json', 'readme.md'];

const CDN_MAP = {
  'https://unpkg.com/react@18.3.1/umd/react.production.min.js': 'vendor/react.production.min.js',
  'https://unpkg.com/react-dom@18.3.1/umd/react-dom.production.min.js': 'vendor/react-dom.production.min.js',
};

// The app component pulls Satoshi from fontshare at runtime; point it at the vendored copy.
const FONT_CDN = 'https://api.fontshare.com/v2/css?f[]=satoshi@1&display=swap';
const FONT_LOCAL = 'vendor/fonts/satoshi.css';

// JSON-encode for embedding inside an inline <script>. The component sources contain their
// own </script> tags, which would otherwise terminate the bootstrap tag early; the HTML parser
// only looks for the literal characters, so escaping the slash is sufficient and JSON-safe.
const enc = (s) =>
  JSON.stringify(s).replace(/<\/(script)/gi, '<\\/$1').replace(/<!--/g, '<\\!--');

/** Bootstrap that must execute before support.js reads the two hooks. */
function bootstrap(componentSources) {
  const blobEntries = Object.entries(componentSources)
    .map(([url, src]) => `  ${enc(url)}: new Blob([${enc(src)}], { type: 'text/html' }),`)
    .join('\n');

  return `<script>
// Generated by build.mjs — redirects the dc-runtime's external lookups to local resources.
window.__resources = {
${Object.entries(CDN_MAP).map(([k, v]) => `  ${enc(k)}: ${enc(v)},`).join('\n')}
};
window.__resourceBlobs = {
${blobEntries}
};
</script>`;
}

async function main() {
  await rm(DIST, { recursive: true, force: true });
  await mkdir(DIST, { recursive: true });

  // Inline each imported component under the exact URL the runtime will ask for:
  // COMPONENT_DIR + "/" + encodeURIComponent(name) + ".dc.html", with COMPONENT_DIR ".".
  const componentSources = {};
  for (const name of COMPONENTS) {
    const src = await readFile(join(ROOT, `${name}.dc.html`), 'utf8');
    componentSources[`./${encodeURIComponent(name)}.dc.html`] = src.replace(FONT_CDN, FONT_LOCAL);
  }

  let html = await readFile(join(ROOT, ENTRY), 'utf8');
  html = html.replace(FONT_CDN, FONT_LOCAL);

  // Drop the tag for the excluded design-system bundle so it doesn't 404 at runtime.
  const dsBundleTag = /<script src="[^"]*_ds_bundle\.js"><\/script>\s*/g;
  if (!dsBundleTag.test(html)) throw new Error('_ds_bundle.js script tag not found — check the export');
  html = html.replace(dsBundleTag, '');

  // Give the page a real title and description; the export had neither. This must happen
  // BEFORE the bootstrap is inserted: the inlined component source contains its own </head>,
  // and a string-pattern replace would otherwise match that one and corrupt the JS literal.
  html = html.replace('</head>', `<title>Spatial Adjust Guides</title>
<meta name="description" content="Interactive guides for the Spatial Adjust feature in IntelliDash.">
<meta name="robots" content="noindex, nofollow">
</head>`);

  // The bootstrap has to land before the support.js tag, not merely before </head>.
  const supportTag = '<script src="./support.js"></script>';
  if (!html.includes(supportTag)) throw new Error('support.js script tag not found in entry document');
  html = html.replace(supportTag, `${bootstrap(componentSources)}\n${supportTag}`);

  await writeFile(join(DIST, 'index.html'), html);
  await cp(join(ROOT, 'support.js'), join(DIST, 'support.js'));
  for (const dir of STATIC_DIRS) {
    await cp(join(ROOT, dir), join(DIST, dir), {
      recursive: true,
      filter: (src) => !DS_EXCLUDE.some((name) => src.endsWith(`/${name}`)),
    });
  }
  await writeFile(join(DIST, 'robots.txt'), 'User-agent: *\nDisallow: /\n');

  console.log(`built dist/ — entry index.html, ${COMPONENTS.length} component(s) inlined, 0 external origins`);
}

await main();
